apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-web
  namespace: quest
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: quest-web
      app: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quest-web
    spec:
      containers:
        - name: quest-web-ctn
          image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/quest-web:0.0.4
          ports:
            - name: http
              containerPort: 80