apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-web
  namespace: web
  labels:
    app: nba-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nba-web
  template:
    metadata:
      labels:
        app: nba-web
    spec:
      containers:
        - name: nba-web
          image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/nba-web:test-1
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          imagePullPolicy: IfNotPresent